version = 5.4.0
archive_dir = /etc/letsencrypt/archive/foxbel.ru
cert = /etc/letsencrypt/live/foxbel.ru/cert.pem
privkey = /etc/letsencrypt/live/foxbel.ru/privkey.pem
chain = /etc/letsencrypt/live/foxbel.ru/chain.pem
fullchain = /etc/letsencrypt/live/foxbel.ru/fullchain.pem
[renewalparams]
account = b41d1db6fd2aab4e2a07cdf805e9c123
pref_challs = http-01,
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
foxbel.ru = /var/www/certbot
[acme_renewal_info]
ari_retry_after = 2026-03-17T19:07:01
